version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
      - ./app/tests:/app/tests

  db:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    restart: always
    env_file: .env
