FROM mongo

# Create a new directory to store the database
RUN mkdir -p /data/db

# change the owner of the database directory
RUN chown -R mongodb:mongodb /data/db
# Expose the MongoDB Port
EXPOSE 27017
# Setup the commands to be run on the container image.
CMD ["mongod", "--bind_ip_all"]
