version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  mongo:
    image: mongo
    ports:
      - "27017:27017"
