version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app #Mount the app local app dir in to the /app in the fastapi container
      - ./tests:/app/tests #Mount local tests dir into /app/tests in the fastapi container
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  db:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    restart: always
    env_file: .env
